Presentation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;

namespace Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet("Contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Shared.Statics.Models;

namespace Presentation.Controllers
{
    public class StoreController : Controller
    {
        private readonly ILogger<StoreController> _logger;

        public StoreController(ILogger<StoreController> logger)
        {
            _logger = logger;
        }

        [HttpGet("Docs")]
        public IActionResult Index(string doctype = "")
        {
            return View();
        }
    }
}

Presentation/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div style="width:700px; margin: 0 auto;" class="big-card">
    <div class="text-center">
        <section>
            <h4>Contact Us</h4>
            <section>

            </section>
            <p>

            </p>
        </section>

    </div>
</div>

Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Free API Store";
    ViewData["Footer-fixed"] = true;
}

<div style="width:500px; margin: 0 auto;">
    <div class="text-center">
        <h4>Welcome to our <b>Free API Store</b>!</h4>
        <p>Dive into a treasure trove of APIs tailored for testing purposes, yet built with the same excellence as those for real-world applications. Here, you can refine your skills in API integration and explore a plethora of possibilities to enrich your development journey.</p>
    </div>
</div>

<div class="custom-container">
    <div class="api-card">
        <h4>E-commerce API</h4>
        <p>Access product information, prices, and images for your online store with oauth</p>
        <a href="@Url.Action("Index", "Store")?doctype=ecommerce">Docs</a>
    </div>
    <div class="api-card">
        <h4>Finance Tracker API</h4>
        <p>Helps users manage their financial activities, such spending, budgeting, and savings.</p>
        @* <a href="@Url.Action("Index", "Store")?doctype=finance-tracker">Docs</a> *@
        <a href="#">Coming Soon</a>
    </div>
    <div class="api-card">
        <h4>Todo API</h4>
        <p>Manages tasks for users, allowing them to perform CRUD on their to-do lists via web requests.</p>
        <a href="@Url.Action("Index", "Store")?doctype=todo">Docs</a>
    </div>
</div>